[package]
name = "exemplo03"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
oracle = "0.5"

[build-dependencies]
pkg-config = "0.3"

cc = "1.0"

[profile.release]
opt-level = "z"
